GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
   event.create("fish_farm")
        .category("multiblock")
        .setEUIO("in")
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.ARROW_INPUT_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MACERATE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.MINER)
})

GTCEuStartupEvents.registry("gtceu:machine", event => {
	
	event.create("fish_farm", "multiblock")
        .recipeTypes("fish_farm")
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .pattern(definition => FactoryBlockPattern.start()
		.aisle("abcbcba", "abdddba", "abdddba")
		.aisle("bbcbcbb", "bbaaabb", "bbaaabb")
		.aisle("cccbccc", "daaaaad", "daaaaad")
		.aisle("bbbbbbb", "daaaaad", "daaaaad")
		.aisle("cccbccc", "daaaaad", "daaaaad")
		.aisle("bbcbcbb", "bbaaabb", "bbaaabb")
		.aisle("abc@cba", "abdddba", "abdddba")
		.where("@", Predicates.controller(Predicates.blocks(definition.get())))
		.where("a", Predicates.blocks("minecraft:air"))
		.where("b", Predicates.blocks("gtceu:stable_machine_casing")
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
				)
		.where("c", Predicates.blocks("gtceu:titanium_pipe_casing"))
		.where("d", Predicates.blocks("gtceu:titanium_frame"))
		.build())
        .workableCasingModel("gtceu:block/casings/gcym/hv_machine_casing",
            "gtceu:block/machines/rock_crusher")
})