GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
   event.create("noom_collection")
        .category("multiblock")
        .setEUIO("in")
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.ARROW_INPUT_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MACERATE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.MINER)
})

GTCEuStartupEvents.registry("gtceu:machine", event => {

    event.create("noom_collection", "multiblock")
        .recipeTypes("noom_collection")
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("abaaaba", "abaaaba", "abaaaba", "abcccba", "accccca", "accccca", "accccca", "aacccaa", "aaaaaaa")
            .aisle("bbaaabb", "bbaaabb", "bbcccbb", "bcdddcb", "cdaaddc", "caaaadc", "caaaaac", "acaaaca", "aacccaa")
            .aisle("aaeaeaa", "aafffaa", "acbgbca", "cddaadc", "caaaaac", "caaaaac", "caaaaac", "caaaaac", "accccca")
            .aisle("aaahaaa", "aafhfaa", "acghgca", "caaaddc", "caaaaac", "caaaaac", "caaaaac", "caaaaac", "accccca")
            .aisle("aaeaeaa", "aaf@faa", "acbgbca", "cddaadc", "caaaaac", "caaaaac", "caaaaac", "caaaaac", "accccca")
            .aisle("bbaaabb", "bbaaabb", "bbcccbb", "bcdddcb", "cddaadc", "cdaaaac", "caaaaac", "acaaaca", "aacccaa")
            .aisle("abaaaba", "abaaaba", "abaaaba", "abcccba", "accccca", "accccca", "accccca", "aacccaa", "aaaaaaa")
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .where("a", Predicates.blocks("minecraft:air"))
            .where("d", Predicates.blocks("genesis:moon_sand"))
            .where("g", Predicates.blocks("gtceu:stainless_steel_gearbox"))
            .where("h", Predicates.blocks("gtceu:steel_pipe_casing"))
            .where("b", Predicates.blocks("gtceu:clean_machine_casing"))
            .where("c", Predicates.blocks("gtceu:tempered_glass"))
            .where("e", Predicates.blocks("gtceu:stainless_steel_frame"))
            .where("f", Predicates.blocks("gtceu:hv_machine_casing")
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
				)
            .build())
        .workableCasingModel("gtceu:block/casings/gcym/hv_machine_casing",
            "gtceu:block/machines/rock_crusher")
})

