GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
   event.create("mass_analyzer")
        .category("multiblock")
        .setEUIO("in")
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.ARROW_INPUT_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MACERATE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.MINER)
})

GTCEuStartupEvents.registry("gtceu:machine", event => {
	
	event.create("mass_analyzer", "multiblock")
        .recipeTypes("mass_analyzer")
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .pattern(definition => FactoryBlockPattern.start()
		.aisle("aaaaaaa", "abbbbba", "aaaaaaa")
		.aisle("aacccaa", "adeeeda", "aaaaaaa")
		.aisle("aaa@aaa", "abbbbba", "aaaaaaa")
		.where("@", Predicates.controller(Predicates.blocks(definition.get())))
		.where("a", Predicates.blocks("gtceu:robust_machine_casing")
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
				)
		.where("b", Predicates.blocks("gtceu:laminated_glass"))
		.where("c", Predicates.blocks("gtceu:slicing_blades"))
		.where("d", Predicates.blocks("gtceu:tungstensteel_gearbox"))
		.where("e", Predicates.blocks("minecraft:air"))
		.build())
        .workableCasingModel("gtceu:block/casings/gcym/hv_machine_casing",
            "gtceu:block/machines/rock_crusher")
})
