GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
   event.create("primordial_extractor")
        .category("multiblock")
        .setEUIO("in")
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.ARROW_INPUT_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MACERATE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.MINER)
})

GTCEuStartupEvents.registry("gtceu:machine", event => {
	
	event.create("primordial_extractor", "multiblock")
        .recipeTypes("primordial_extractor")
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .pattern(definition => FactoryBlockPattern.start()
			.aisle("abbba", "acdca", "aabaa", "aabaa", "abbba", "aaaaa", "aaaaa", "aaaaa")
			.aisle("bbbbb", "ccdcc", "aedea", "aedea", "bbdbb", "aadaa", "aadaa", "aafaa")
			.aisle("bbbbb", "ddedd", "bdedb", "bdedb", "bdedb", "adeda", "adeda", "afffa")
			.aisle("bbbbb", "ccdcc", "aedea", "aedea", "bbdbb", "aadaa", "aadaa", "aafaa")
			.aisle("ab@ba", "acdca", "aabaa", "aabaa", "abbba", "aaaaa", "aaaaa", "aaaaa")
			.where("@", Predicates.controller(Predicates.blocks(definition.get())))
			.where("a", Predicates.blocks("minecraft:air"))
			.where("b", Predicates.blocks("gtceu:robust_machine_casing")
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
				)
			.where("c", Predicates.blocks("gtceu:tungstensteel_firebox_casing"))
			.where("d", Predicates.blocks("gtceu:heat_vent"))
			.where("e", Predicates.blocks("gtceu:tungstensteel_gearbox"))
			.where("f", Predicates.blocks("gtceu:tungsten_steel_frame"))
			.build())
        .workableCasingModel("gtceu:block/casings/gcym/hv_machine_casing",
            "gtceu:block/machines/rock_crusher")
})