GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
   event.create("vent_feeder")
        .category("multiblock")
        .setEUIO("in")
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.ARROW_INPUT_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MACERATE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.MINER)
})

GTCEuStartupEvents.registry("gtceu:machine", event => {
	
	event.create("vent_feeder", "multiblock")
        .recipeTypes("vent_feeder")
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .pattern(definition => FactoryBlockPattern.start()
			.aisle("aaa", "aba", "aba", "aaa")
			.aisle("cac", "ded", "ded", "aaa")
			.aisle("@ac", "dfd", "ded", "aaa")
			.aisle("cac", "ded", "ded", "aaa")
			.aisle("aaa", "aba", "aba", "aaa")
			.where("@", Predicates.controller(Predicates.blocks(definition.get())))
			.where("a", Predicates.blocks("gtceu:stable_machine_casing")
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
				)
			.where("b", Predicates.blocks("gtceu:titanium_gearbox"))
			.where("c", Predicates.blocks("gtceu:titanium_firebox_casing"))
			.where("d", Predicates.blocks("gtceu:laminated_glass"))
			.where("e", Predicates.blocks("minecraft:air"))
			.where("f", Predicates.blocks("kubejs:hydrothermalvent"))
			.build())
        .workableCasingModel("gtceu:block/casings/gcym/hv_machine_casing",
            "gtceu:block/machines/rock_crusher")
})

